spring.application.name=webplatform

spring.datasource.url=jdbc:postgresql://localhost:5430/dered
spring.datasource.username=webapp
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=8

jwt.secret=bfwugvwygvwyogvwegvergvervgerveeeeeeeeevyftu0eeeeeeeeewyfewfgwerf
jwt.access-token-expiration=90000
jwt.refresh-token-expiration=259200000

